version: "3"
services:
  db:
    container_name: pr1_db
    image: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ./server:/docker-entrypoint-initdb.d
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
  server:
    container_name: pr1_server
    build: ./server
    volumes:
      - ./server:/var/www/html
    ports:
      - "8080:80"